# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [151]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [152]:
sinasc_raw = pd.read_csv('SINASC_RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [153]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')

In [154]:
sinasc_1= sinasc_raw[['IDADEMAE', 'IDADEPAI', 'munResNome']]

In [155]:
sinasc_2= sinasc_raw[['ESCMAE', 'SEXO', 'PESO', 'DTNASC']]

In [156]:
sinasc_3= sinasc_raw[['IDADEMAE', 'IDADEPAI', 'munResNome', 'DTNASC', 'QTDFILVIVO']]

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [157]:
sinasc_1.groupby('munResNome').agg([('média','mean')]) #separa pelo índice município e aplica a média nas demais variáveis numéricas

                            IDADEMAE   IDADEPAI
                               média      média
munResNome
Alta Floresta D'Oeste      25.991826  29.548701
Alto Alegre dos Parecis    24.844156  29.179104
Alto Paraíso               24.960177  28.833333
Alvorada D'Oeste           25.770732  30.757282
Ariquemes                  25.607866  32.466667
Buritis                    25.559177  30.812500
Cabixi                     26.037500  34.333333
Cacaulândia                25.546667  36.333333
Cacoal                     26.890102  30.931854
Campo Novo de Rondônia     24.825301  30.500000
Candeias do Jamari         25.243323  29.894737
Castanheiras               27.281250  30.392857
Cerejeiras                 27.240506  31.652778
Chupinguaia                25.333333  29.629630
Colorado do Oeste          27.602804  34.354839
Corumbiara                 24.716535  32.470588
Costa Marques              24.412017  30.613636
Cujubim                    24.482927  31.400000
Espigão D'Oeste            26.093333  31.198113
Governador Jorge Teixeira  24.401786  29.222222
Guajará-Mirim              25.462228  30.470588
Itapuã do Oeste            26.064220  42.500000
Jaru                       25.982974  32.197183
Ji-Paraná                  26.361137  31.132239
Machadinho D'Oeste         25.480000  31.326923
Ministro Andreazza         27.904762  33.849315
Mirante da Serra           26.304878  32.154762
Monte Negro                25.648241  34.678571
Município ignorado - RO    24.000000  22.000000
Nova Brasilândia D'Oeste   26.222222  30.520833
Nova Mamoré                25.326389  31.692308
Nova União                 26.894231  31.371429
Novo Horizonte do Oeste    26.938776  31.588235
Ouro Preto do Oeste        26.375594  31.233244
Parecis                    26.454545  32.473684
Pimenta Bueno              25.199675  29.745174
Pimenteiras do Oeste       25.075000  35.600000
Porto Velho                26.312670  32.352679
Presidente Médici          25.796053  30.150754
Primavera de Rondônia      27.023256  31.888889
Rio Crespo                 26.660000  28.000000
Rolim de Moura             26.600863  30.360479
Santa Luzia D'Oeste        26.121212  30.703297
Seringueiras               24.910714  30.500000
São Felipe D'Oeste         26.481481  31.395833
São Francisco do Guaporé   25.660066  31.638889
São Miguel do Guaporé      25.926346  32.666667
Teixeirópolis              26.031250  31.500000
Theobroma                  25.536082  30.083333
Urupá                      26.688235  31.008929
Vale do Anari              26.096774  34.000000
Vale do Paraíso            25.679012  29.976744
Vilhena                    26.433962  34.152941

A idade média das mães é maior no município de Ministro Andreazza, enquanto que a dos pais é maior no município de Itapuã do Oeste. Vale ressaltar que a idade média dos pais de Itapuã do Oeste é bem superior a idade média dos pais dos demais municípios registrados. Também a discrepância entre a idade média dos pais é muito superior à idade média das mães.

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [158]:
#sinasc_2= sinasc_raw[['ESCMAE', 'SEXO', 'PESO', 'DTNASC']]

In [159]:
#primeiro o loc para filtrar e depois, com o filtro aplicado, usa o groupby para as variáveis categóricas de interesse e aplica a média no peso.
(sinasc_2.loc[(sinasc_2['DTNASC']=='2019-10-22')]).groupby(['DTNASC','ESCMAE', 'SEXO']).agg([('média', 'mean')])

                                             PESO
                                            média
DTNASC     ESCMAE          SEXO
2019-10-22 12 anos ou mais Feminino   3347.777778
                           Masculino  3244.000000
           4 a 7 anos      Feminino   3360.750000
                           Masculino  3506.000000
           8 a 11 anos     Feminino   3250.947368
                           Masculino  3155.000000

No df acima, a única faixa de estudo das mães em que o peso do sexo feminino não é superior ao do masculino é a faixa de estudo entre 4 a 7 anos.

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [160]:
#sinasc_1= sinasc_raw[['IDADEMAE', 'IDADEPAI', 'munResNome']]

In [161]:
#descobrindo qual é o município com menos nascimentos, para isso um value counts em ordem crescente
sinasc_1.munResNome.value_counts().sort_values(ascending=True)[:2]

Município ignorado - RO     1
Castanheiras               32
Name: munResNome, dtype: int64

Como acima o município com menos nascimentos é um município ignorado, vamos utilizar Castanheiras.

In [162]:
#procurando Castanheiras entre os municípios e aplicando o groupby e o aggregate
(sinasc_1.loc[(sinasc_1['munResNome']=='Castanheiras')]).groupby(['munResNome']).aggregate([('minimo', 'min'), ('média', 'mean'), ('máximo',max)])

             IDADEMAE                  IDADEPAI
               minimo     média máximo   minimo      média máximo
munResNome
Castanheiras       17  27.28125     39     17.0  30.392857   43.0

O municipio de Castanheiras tem a mesma idade mínima para pai e mãe, enquanto que a idade máxima difere de 4 anos.

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [163]:
sinasc_3.dtypes

IDADEMAE        int64
IDADEPAI      float64
munResNome     object
DTNASC         object
QTDFILVIVO    float64
dtype: object

In [169]:
#transformando a dtnasc para datetime, com o objetivo de posteriormente utilizar o atributo month
sinasc_3.loc[:,'DTNASC'] = pd.to_datetime(sinasc_3['DTNASC'])

/tmp/ipykernel_5514/1133043806.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sinasc_3.loc[:,'DTNASC'] = pd.to_datetime(sinasc_3['DTNASC'])

In [170]:
#visualizando qual a frequência que cada município aparece no mês três (março)
(sinasc_3[sinasc_3['DTNASC'].dt.month == 3]).munResNome.value_counts()

Porto Velho                  744
Ji-Paraná                    188
Vilhena                      148
Ariquemes                    141
Cacoal                       133
Jaru                          80
Guajará-Mirim                 75
Rolim de Moura                69
Ouro Preto do Oeste           67
Pimenta Bueno                 62
Buritis                       59
Nova Mamoré                   53
Machadinho D'Oeste            44
Espigão D'Oeste               44
São Miguel do Guaporé         41
Candeias do Jamari            33
São Francisco do Guaporé      31
Alta Floresta D'Oeste         31
Presidente Médici             29
Costa Marques                 24
Alto Paraíso                  22
Alvorada D'Oeste              22
Monte Negro                   20
Nova Brasilândia D'Oeste      20
Seringueiras                  19
Colorado do Oeste             19
Chupinguaia                   18
Cujubim                       17
Cerejeiras                    16
Urupá                         14
Vale do Paraíso               13
Campo Novo de Rondônia        13
Corumbiara                    12
Vale do Anari                 11
Governador Jorge Teixeira     10
Alto Alegre dos Parecis       10
Cacaulândia                   10
Mirante da Serra               9
Rio Crespo                     9
Theobroma                      8
Itapuã do Oeste                8
Santa Luzia D'Oeste            7
Nova União                     7
Pimenteiras do Oeste           6
Cabixi                         6
Parecis                        6
Ministro Andreazza             6
Primavera de Rondônia          5
Novo Horizonte do Oeste        5
São Felipe D'Oeste             5
Castanheiras                   4
Teixeirópolis                  3
Name: munResNome, dtype: int64

Acima podemos ver que o município com o maior número de registros no mês de março é Porto Velho.

In [171]:
#criando uma nova variável chamada mês março para por apenas o filtro do mês 3
mes_marco= sinasc_3[sinasc_3['DTNASC'].dt.month == 3]

In [172]:
#observando se salvou as demais colunas que haviam no sinasc_3, contendo o filtro do mes de março
mes_marco

       IDADEMAE  IDADEPAI               munResNome     DTNASC  QTDFILVIVO
3            30      24.0  Alto Alegre dos Parecis 2019-03-20         0.0
4            30      27.0    Alta Floresta D'Oeste 2019-03-23         1.0
5            33      40.0    Alta Floresta D'Oeste 2019-03-27         2.0
9            30      41.0    Alta Floresta D'Oeste 2019-03-11         1.0
10           31      28.0    Alta Floresta D'Oeste 2019-03-11         1.0
...         ...       ...                      ...        ...         ...
13670        24       NaN              Porto Velho 2019-03-21         0.0
13671        24       NaN              Porto Velho 2019-03-22         2.0
13736        35      42.0              Porto Velho 2019-03-07         1.0
13748        36       NaN                  Vilhena 2019-03-30         2.0
13750        31      50.0                Ji-Paraná 2019-03-09         0.0

[2456 rows x 5 columns]

In [173]:
#no mês março, filtrando apenas o muniípio com maior registros, que como visto acima é Porto Velho e aplcando max, min e média as demais categorias numéricas. 
(mes_marco[mes_marco['munResNome'] == 'Porto Velho']).groupby(['DTNASC', 'munResNome']).aggregate([('minimo', 'min'), ('média', 'mean'), ('máximo',max)])

                       IDADEMAE                   IDADEPAI                    \
                         minimo      média máximo   minimo      média máximo
DTNASC     munResNome
2019-03-01 Porto Velho       15  28.343750     44     33.0  40.200000   51.0
2019-03-02 Porto Velho       14  26.285714     38     25.0  32.000000   38.0
2019-03-03 Porto Velho       17  28.285714     42     34.0  34.000000   34.0
2019-03-04 Porto Velho       16  27.650000     43     30.0  33.800000   38.0
2019-03-05 Porto Velho       15  26.000000     38     39.0  39.000000   39.0
2019-03-06 Porto Velho       16  26.095238     37     35.0  35.000000   35.0
2019-03-07 Porto Velho       16  27.350000     42     31.0  41.666667   52.0
2019-03-08 Porto Velho       17  28.095238     42     31.0  31.000000   31.0
2019-03-09 Porto Velho       17  24.777778     38     26.0  31.000000   37.0
2019-03-10 Porto Velho       16  25.000000     39      NaN        NaN    NaN
2019-03-11 Porto Velho       15  27.129032     41     28.0  32.250000   40.0
2019-03-12 Porto Velho       15  28.222222     39      NaN        NaN    NaN
2019-03-13 Porto Velho       17  26.333333     37     35.0  36.000000   37.0
2019-03-14 Porto Velho       16  27.578947     42     31.0  31.000000   31.0
2019-03-15 Porto Velho       15  27.088235     40     23.0  31.600000   38.0
2019-03-16 Porto Velho       16  26.290323     44     19.0  26.333333   34.0
2019-03-17 Porto Velho       16  24.500000     36     24.0  32.000000   40.0
2019-03-18 Porto Velho       14  26.137931     40     21.0  34.666667   51.0
2019-03-19 Porto Velho       18  29.043478     41     49.0  51.000000   53.0
2019-03-20 Porto Velho       18  27.666667     43      NaN        NaN    NaN
2019-03-21 Porto Velho       15  25.464286     40     44.0  44.000000   44.0
2019-03-22 Porto Velho       19  26.736842     41     23.0  23.000000   23.0
2019-03-23 Porto Velho       16  27.894737     40     29.0  29.000000   29.0
2019-03-24 Porto Velho       17  25.391304     39     30.0  40.000000   55.0
2019-03-25 Porto Velho       16  25.880000     38      NaN        NaN    NaN
2019-03-26 Porto Velho       17  26.760000     40     26.0  27.000000   28.0
2019-03-27 Porto Velho       15  27.680000     44     20.0  41.000000   62.0
2019-03-28 Porto Velho       16  26.290323     40     30.0  35.666667   39.0
2019-03-29 Porto Velho       16  24.880000     35      NaN        NaN    NaN
2019-03-30 Porto Velho       15  28.368421     39      NaN        NaN    NaN
2019-03-31 Porto Velho       14  22.352941     43      NaN        NaN    NaN

                       QTDFILVIVO
                           minimo     média máximo
DTNASC     munResNome
2019-03-01 Porto Velho        0.0  1.322581    3.0
2019-03-02 Porto Velho        0.0  1.434783    4.0
2019-03-03 Porto Velho        0.0  1.400000    3.0
2019-03-04 Porto Velho        0.0  1.600000    4.0
2019-03-05 Porto Velho        0.0  1.652174    5.0
2019-03-06 Porto Velho        0.0  1.285714    4.0
2019-03-07 Porto Velho        0.0  1.416667    7.0
2019-03-08 Porto Velho        0.0  1.588235    4.0
2019-03-09 Porto Velho        0.0  1.000000    2.0
2019-03-10 Porto Velho        0.0  1.214286    3.0
2019-03-11 Porto Velho        0.0  1.222222    4.0
2019-03-12 Porto Velho        0.0  1.533333    5.0
2019-03-13 Porto Velho        0.0  1.222222    5.0
2019-03-14 Porto Velho        0.0  1.562500    6.0
2019-03-15 Porto Velho        0.0  1.193548    4.0
2019-03-16 Porto Velho        0.0  1.523810    6.0
2019-03-17 Porto Velho        0.0  1.562500    3.0
2019-03-18 Porto Velho        0.0  1.600000    6.0
2019-03-19 Porto Velho        0.0  1.235294    4.0
2019-03-20 Porto Velho        0.0  1.315789    6.0
2019-03-21 Porto Velho        0.0  1.153846    5.0
2019-03-22 Porto Velho        0.0  0.944444    2.0
2019-03-23 Porto Velho        0.0  1.000000    6.0
2019-03-24 Porto Velho        0.0  0.818182    2.0
2019-03-25 Porto Velho        0.0  1.041667    9.0
2019-03-26 Porto Velho        0.0  1.217391    5.0
2019-03-27 Porto Velho        0.0  1.960000    6.0
2019-03-28 Porto Velho        0.0  0.933333    4.0
2019-03-29 Porto Velho        0.0  1.080000    5.0
2019-03-30 Porto Velho        0.0  1.789474    5.0
2019-03-31 Porto Velho        0.0  0.588235    2.0

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

Exemplo:
- Ah, descobri que a idade mediana das mulheres que deram a luz no ano de 2019 dos municipios x é maior que y.

In [174]:
sinasc_raw.dtypes

ORIGEM          int64
CODESTAB      float64
CODMUNNASC      int64
LOCNASC         int64
IDADEMAE        int64
               ...
munResUf       object
munResLat     float64
munResLon     float64
munResAlt     float64
munResArea    float64
Length: 69, dtype: object

In [175]:
sinasc_raw.select_dtypes(exclude=['int64','float64'])

,ESCMAE,GESTACAO,GRAVIDEZ,PARTO,DTNASC,SEXO,RACACOR,DTCADASTRO,CODANOMAL,VERSAOSIST,DTRECEBIM,munResStatus,munResTipo,munResNome,munResUf
0,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-19,Masculino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
1,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-21,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
2,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-25,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
3,12 anos ou mais,37 a 41 semanas,Única,Cesáreo,2019-03-20,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia
4,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-03-23,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27023,12 anos ou mais,32 a 36 semanas,Única,Cesáreo,2019-12-13,Masculino,Branca,2020-09-28,NaN,3.2.01,2020-10-13,ATIVO,MUNIC,Vilhena,Rondônia
27024,8 a 11 anos,37 a 41 semanas,Única,Vaginal,2019-10-04,Masculino,Branca,2019-10-16,NaN,3.2.01,2019-10-21,ATIVO,MUNIC,Chupinguaia,Rondônia
27025,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-08-02,Masculino,Parda,2019-08-07,NaN,3.2.00,2019-08-07,ATIVO,MUNIC,Vilhena,Rondônia
27026,8 a 11 anos,32 a 36 semanas,Única,Vaginal,2019-12-23,Masculino,Parda,2020-01-07,NaN,3.2.00,2020-01-07,ATIVO,MUNIC,Vilhena,Rondônia
27027,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-12-27,Masculino,Parda,2020-10-15,NaN,3.2.01,2020-10-16,ATIVO,MUNIC,Novo Horizonte do Oeste,Rondônia

In [176]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')